name: go_food
description: A new experience!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  expandable: ^5.0.1
  http: ^0.13.5
  badges: ^2.0.3
  provider: ^6.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  mobx_codegen: ^2.0.7
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  mockito: ^5.0.10
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/